import { AccessibilityBar } from "./components/accessibility-bar";
import { Footer } from "./components/footer";
import { Atkinson_Hyperlegible, Atkinson_Hyperlegible } from "next/font/google";
const atkinson_Hyperlegible = Atkinson_Hyperlegible({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "SEMITEC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={atkinson_Hyperlegible.className} style={ {margin: "0px"}}>
        {children}
        {<Footer />}
      </body>
    </html>
  );
}
